#!/bin/bash


# Remplace les noms d'exécutables par les tiens
build/Debug/white.exe
build/Debug/vert.exe
build/Debug/swap.exe
build/Debug/nETb.exe
build/Debug/invert.exe
build/Debug/degrade.exe
build/Debug/miroir.exe
build/Debug/miroirDouble.exe
build/Debug/bruit.exe
build/Debug/rotate90.exe
build/Debug/rotateWeird.exe
build/Debug/virtualiser.exe
build/Debug/split.exe
build/Debug/splitXcropped.exe
build/Debug/luminosity.exe
build/Debug/luminosity.exe
build/Debug/disque.exe
build/Debug/cercle.exe
build/Debug/rosace.exe
build/Debug/disqueWeird.exe
build/Debug/mosaique.exe
build/Debug/mosaiqueMiroir.exe
build/Debug/glitch.exe
build/Debug/fractale.exe
build/Debug/vortex.exe
build/Debug/vortex-fail-1.exe
build/Debug/vortex-fail-2.exe
build/Debug/vortex-fail-3.exe
build/Debug/vortex-fail-4.exe
build/Debug/vortex-fail-5.exe
build/Debug/vortex-fail-6.exe
build/Debug/vortex-fail-7.exe
build/Debug/vortex-fail-8.exe
build/Debug/vortex-fail-9.exe
build/Debug/vortex-fail-10.exe
build/Debug/vortex-fail-11.exe
build/Debug/normalisation.exe
build/Debug/normalisation-lum.exe
build/Debug/tri.exe
build/Debug/tri-double.exe
build/Debug/tri-brightness.exe
build/Debug/tri-brightness-all.exe
build/Debug/tri-brightness-vertical.exe
build/Debug/tri-random-brightness.exe
build/Debug/tri-hue.exe
build/Debug/tri-hue-all.exe
build/Debug/tri-random-hue.exe
build/Debug/kmeans.exe
build/Debug/kmeans-gpt.exe
# Ajoute d'autres exécutables si nécessaire